package ovh.piwowarczyk.votr;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * <p>Główna klasa aplikacji</p>
 *
 * @author autogenerated
 */
@SpringBootApplication
public class VotrApplication {

    /**
     * <p>Główna metoda uruchamiająca aplikację</p>
     *
     * @param args lista obiektów typu  {@link String}.
     */
    public static void main(String[] args) {
        SpringApplication.run(VotrApplication.class, args);
    }

}
